name: Markdown to HTML

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Convert Markdown to HTML
      uses: ./ # Uses an action in the root directory
